version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./god-back/
    ports:
      - "6200:6200"
    volumes:
      - ./god-back:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./god-front/
    ports:
      - "3000:3000"
    volumes:
      - ./god-front:/usr/src/app
    depends_on:
      - backend